name: Build & Release ValidStart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Build ValidStart CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build binaries
        run: |
          pkg dist/index.js --targets node18-linux-x64 --output validstart-linux
          pkg dist/index.js --targets node18-macos-x64 --output validstart-macos
          pkg dist/index.js --targets node18-win-x64 --output validstart-win.exe

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            validstart-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
