name: Build & Release ValidStart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Build ValidStart CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install nexe
        run: npm install -g nexe

      - name: Build binary
        shell: bash
        run: |
          echo "🔧 Building for: $RUNNER_OS"
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            nexe ./index.js -t linux-x64-22.0.0 --build -o validstart-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            nexe ./index.js -t macos-x64-22.0.0 --build -o validstart-macos
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            nexe ./index.js -t windows-x64-22.0.0 --build -o validstart-win.exe
          else
            echo "❌ Unsupported OS: $RUNNER_OS"
            exit 1
          fi

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            validstart-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
